-- =====================================================================
-- create_load.sql
-- Darwin Art Company - Online Art Store
-- HIT326 Group 21 Project
--
-- This script creates the database, all tables, indexes, foreign keys,
-- and loads initial seed data so the application is runnable immediately
-- after installation.
--
-- Run with:  mysql -u root -p < create_load.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- Database
-- ---------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS darwin_art
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE darwin_art;

-- ---------------------------------------------------------------------
-- Drop existing tables (reverse FK order so re-runs work cleanly)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS testimonial;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS purchase_item;
DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS admin;

-- ---------------------------------------------------------------------
-- Table: admin
-- Stores administrator accounts. Passwords are stored as bcrypt hashes
-- generated by PHP's password_hash() function.
-- ---------------------------------------------------------------------
CREATE TABLE admin (
    admin_id      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (admin_id),
    UNIQUE KEY uq_admin_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: product
-- Catalogue of artworks for sale. `is_available` provides soft-delete
-- so historical orders referencing removed products remain valid.
-- ---------------------------------------------------------------------
CREATE TABLE product (
    product_id     INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    name           VARCHAR(150)   NOT NULL,
    description    TEXT,
    price          DECIMAL(10, 2) NOT NULL,
    category       VARCHAR(50)    DEFAULT NULL,
    color          VARCHAR(50)    DEFAULT NULL,
    size           VARCHAR(50)    DEFAULT NULL,
    image_filename VARCHAR(255)   DEFAULT NULL,
    is_available   TINYINT(1)     NOT NULL DEFAULT 1,
    created_at     DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id),
    KEY idx_product_category (category),
    KEY idx_product_available (is_available)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: customer
-- One row per unique email (guest checkout model). Address is NOT here;
-- it is snapshotted per-order on the purchase table.
-- ---------------------------------------------------------------------
CREATE TABLE customer (
    customer_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email       VARCHAR(255) NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    phone       VARCHAR(30)  DEFAULT NULL,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (customer_id),
    UNIQUE KEY uq_customer_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: purchase
-- Order header. `delivery_address` is captured per-order so updates to
-- the customer record never alter past shipping records.
-- ---------------------------------------------------------------------
CREATE TABLE purchase (
    purchase_id      INT UNSIGNED                      NOT NULL AUTO_INCREMENT,
    customer_id      INT UNSIGNED                      NOT NULL,
    purchase_date    DATETIME                          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount     DECIMAL(10, 2)                    NOT NULL,
    delivery_address TEXT                              NOT NULL,
    status           ENUM('pending', 'confirmed')      NOT NULL DEFAULT 'pending',
    PRIMARY KEY (purchase_id),
    KEY idx_purchase_customer (customer_id),
    KEY idx_purchase_date (purchase_date),
    CONSTRAINT fk_purchase_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: purchase_item
-- Line items in a purchase. `unit_price` is a snapshot of the price at
-- the time of sale so future price changes don't corrupt order history.
-- ---------------------------------------------------------------------
CREATE TABLE purchase_item (
    purchase_item_id INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    purchase_id      INT UNSIGNED   NOT NULL,
    product_id       INT UNSIGNED   NOT NULL,
    quantity         INT UNSIGNED   NOT NULL DEFAULT 1,
    unit_price       DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (purchase_item_id),
    KEY idx_pi_purchase (purchase_id),
    KEY idx_pi_product  (product_id),
    CONSTRAINT fk_pi_purchase
        FOREIGN KEY (purchase_id) REFERENCES purchase (purchase_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_pi_product
        FOREIGN KEY (product_id) REFERENCES product (product_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: news
-- Admin-posted news items. Only the most recent is shown publicly via
-- ORDER BY posted_at DESC LIMIT 1 -- no archive is exposed.
-- ---------------------------------------------------------------------
CREATE TABLE news (
    news_id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    admin_id  INT UNSIGNED DEFAULT NULL,
    title     VARCHAR(200) NOT NULL,
    content   TEXT         NOT NULL,
    posted_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (news_id),
    KEY idx_news_posted (posted_at),
    CONSTRAINT fk_news_admin
        FOREIGN KEY (admin_id) REFERENCES admin (admin_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Table: testimonial
-- Customer-submitted testimonials. Default status is 'pending'; an
-- admin must approve them before they appear on the public testimonials
-- page. `moderated_by` / `moderated_at` form an accountability trail.
-- ---------------------------------------------------------------------
CREATE TABLE testimonial (
    testimonial_id INT UNSIGNED                                 NOT NULL AUTO_INCREMENT,
    customer_name  VARCHAR(100)                                 NOT NULL,
    email          VARCHAR(255)                                 DEFAULT NULL,
    content        TEXT                                         NOT NULL,
    status         ENUM('pending', 'approved', 'rejected')      NOT NULL DEFAULT 'pending',
    submitted_at   DATETIME                                     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    moderated_by   INT UNSIGNED                                 DEFAULT NULL,
    moderated_at   DATETIME                                     DEFAULT NULL,
    PRIMARY KEY (testimonial_id),
    KEY idx_testimonial_status (status),
    CONSTRAINT fk_testimonial_admin
        FOREIGN KEY (moderated_by) REFERENCES admin (admin_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================================
-- Seed data
-- =====================================================================

-- ---------------------------------------------------------------------
-- Default admin account
-- Username: admin
-- Password: Admin@2025
-- The hash below was generated with PHP: password_hash('Admin@2025', PASSWORD_DEFAULT)
-- (bcrypt, cost factor 10). Change the password from inside the admin
-- panel before showing this to anyone real.
-- ---------------------------------------------------------------------
INSERT INTO admin (username, password_hash) VALUES
('admin', '$2y$10$0MqcYmBlN1Nvk30qwWBw2ex6J8fBNQbtRc1DAECGHWnoQ2kHvkPQ6');

-- ---------------------------------------------------------------------
-- Sample artworks (10 items across several categories)
-- ---------------------------------------------------------------------
INSERT INTO product (name, description, price, category, color, size, image_filename, is_available) VALUES
('Sunset over Mindil',     'Acrylic on canvas capturing Darwin''s famous Mindil Beach sunset.', 450.00, 'Painting',    'Orange', '60x80cm',  'sunset_mindil.jpg',      1),
('Kakadu Wetlands',        'Watercolour landscape of Kakadu wetlands at dawn.',                 380.00, 'Painting',    'Green',  '50x70cm',  'kakadu_wetlands.jpg',    1),
('Tropical Storm',         'Oil painting depicting a Top End wet-season thunderstorm.',         620.00, 'Painting',    'Blue',   '80x100cm', 'tropical_storm.jpg',     1),
('Mangrove Roots',         'Black and white photographic print on archival paper.',             220.00, 'Photography', 'Black',  '40x50cm',  'mangrove_roots.jpg',     1),
('Crocodile Dreaming',     'Indigenous-inspired dot painting on canvas.',                       750.00, 'Painting',    'Earth',  '70x90cm',  'crocodile_dreaming.jpg', 1),
('Banyan Tree Study',      'Charcoal sketch on heavyweight paper.',                             180.00, 'Drawing',     'Grey',   '30x40cm',  'banyan_tree.jpg',        1),
('Frangipani Bloom',       'Mixed media on wood panel.',                                        290.00, 'Mixed Media', 'White',  '40x40cm',  'frangipani.jpg',         1),
('Litchfield Falls',       'Long-exposure photographic print of Wangi Falls.',                  260.00, 'Photography', 'Blue',   '50x70cm',  'litchfield_falls.jpg',   1),
('Saltwater Country',      'Abstract expressionist piece in deep blues and greens.',            540.00, 'Painting',    'Blue',   '60x80cm',  'saltwater_country.jpg',  1),
('Termite Mound Field',    'Aerial photographic print of magnetic termite mounds.',             310.00, 'Photography', 'Brown',  '50x70cm',  'termite_mounds.jpg',     1);

-- ---------------------------------------------------------------------
-- Sample news item (the public homepage shows the latest one only)
-- ---------------------------------------------------------------------
INSERT INTO news (admin_id, title, content) VALUES
(1,
 'New Wet Season Collection Now Available',
 'We are thrilled to launch our new Wet Season Collection, featuring ten original works inspired by the dramatic landscapes and storms of Darwin''s Top End. Available now in our online store.');

-- ---------------------------------------------------------------------
-- Sample approved testimonial (so the testimonials page isn't empty
-- on first install)
-- ---------------------------------------------------------------------
INSERT INTO testimonial (customer_name, email, content, status, moderated_by, moderated_at) VALUES
('Sarah J.',
 'sarah.j@example.com',
 'Beautiful work and incredibly fast delivery. The piece looks even better in person -- thank you!',
 'approved',
 1,
 CURRENT_TIMESTAMP);

-- =====================================================================
-- Done
-- =====================================================================
SELECT 'Database darwin_art created and seeded successfully.' AS status;
